site_name: USTC OSH 2023 课程主页
repo_name: OSH-2023/OSH-2023.github.io
repo_url: https://github.com/OSH-2023/OSH-2023.github.io
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'zh'
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.def_list
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_css:
  # Borrow CSS from Linux 101 still
  - 'https://101.ustclug.org/css/extra.css'
nav:
  - 首页: README.md
  - 实验零: lab0/README.md
  - FAQ: faq/README.md
extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
